export { resolveModel, type ResolvedModel } from "./inference/resolver.ts";
export { createAgent, type CreateAgentOptions } from "./agent/factory.ts";
export {
  loadConfig,
  saveConfig,
  ensureHome,
  configExists,
  makeDefaultConfig,
  type LoadedConfig,
} from "./config/loader.ts";
export {
  runShell,
  formatShellResult,
  readFile,
  writeFile,
  editFile,
  listFiles,
  type ShellResult,
  type RunShellOptions,
  type ReadFileOptions,
  type EditFileOptions,
  type EditFileResult,
  type ListFilesResult,
} from "./exec/index.ts";
export { builtinTools } from "./tools/index.ts";
export {
  getSoulPath,
  readSoul,
  soulExists,
  parseSoulSections,
  updateSoulSection,
  appendReflection,
  renderDefaultSoul,
  type SoulSection,
  type UpdateSectionResult,
} from "./soul/index.ts";
export {
  openSharedDb,
  closeSharedDb,
  withDb,
  registerAgent,
  getAgent,
  listAgents,
  updateAgentStatus,
  deleteAgent,
  adjustBudget,
  transferBudget,
  recordTurn,
  listTurns,
  listTurnsBySession,
  countTurns,
  getRecentHistory,
  type CreateAgentInput,
  type RecordTurnInput,
  type TransferResult,
  type ChatMessage,
  type TaskStatus,
  type Task,
  type CreateTaskInput,
  type ClaimResult,
  type CompleteResult,
  createTask,
  getTask,
  listTasks,
  claimTask,
  completeTask,
  failTask,
  abandonTask,
  countTasks,
} from "./state/index.ts";
export {
  initAgentWorkspace,
  getAgentWorkspacePath,
  type InitWorkspaceOptions,
} from "./workspace/index.ts";
export {
  writeMemory,
  searchMemory,
  listMemories,
  getMemory,
  deleteMemory,
  countMemories,
  formatMemoryForPrompt,
  type MemoryType,
  type MemoryRecord,
  type WriteMemoryInput,
  type SearchMemoryOptions,
  type ListMemoriesOptions,
} from "./memory/index.ts";
export {
  sendMessage,
  checkInbox,
  markRead,
  markAllRead,
  countUnread,
  listConversations,
  type MessageType,
  type AgentMessage,
  type SendMessageInput,
  type CheckInboxOptions,
  type Conversation,
} from "./messaging/index.ts";
export {
  spawnAgent,
  stopAgent,
  getProcessInfo,
  listProcesses,
  type SpawnAgentOptions,
  type SpawnedProcess,
  type ProcessInfo,
} from "./process/index.ts";
export {
  getParent,
  getChildren,
  getAncestors,
  getDescendants,
  getRoots,
  getSiblings,
  getLineageTree,
  getLineageSummary,
  getBudget,
  type LineageNode,
  type LineageSummary,
} from "./lineage/index.ts";
export { spawnChild, type SpawnChildInput, type SpawnChildResult } from "./replication/index.ts";
export {
  getModelPrice,
  chargeInference,
  calculateTier,
  applyTierTransition,
  getBudgetSnapshot,
  fundAgent,
  getAgentBudgets,
  TIER_THRESHOLDS,
  type ModelPrice,
  type ChargeInput,
  type ChargeResult,
  type TierTransitionResult,
  type BudgetSnapshot,
} from "./economy/index.ts";
export {
  recordReputationEvent,
  calculateReputation,
  listReputationEvents,
  bulkReputation,
  EVENT_DELTAS,
  type ReputationEventType,
  type ReputationEvent,
  type RecordEventInput,
  type ReputationScore,
} from "./reputation/index.ts";
export {
  saveFossil,
  getFossil,
  getFossilByAgent,
  listFossils,
  searchFossils,
  countFossils,
  deleteFossil,
  distillAgent,
  extractKeywords,
  selectRelevantFossils,
  inheritFossilsIntoMemory,
  type Fossil,
  type SaveFossilInput,
  type SearchFossilsOptions,
  type DistillOptions,
  type DistillResult,
  type InheritedFossil,
} from "./fossils/index.ts";
export {
  listSkills,
  getActiveSkills,
  installSkill,
  removeSkill,
  setSkillEnabled,
  renderSkill,
  type Skill,
  type InstallSkillInput,
} from "./skills/index.ts";
export {
  installPackage,
  writeWorkspaceFile,
  readWorkspaceFile,
  deleteWorkspaceFile,
  listWorkspaceFiles,
  listModifications,
  type ModificationKind,
  type ModificationRecord,
  type InstallPackageResult,
  type WriteFileResult,
  type WorkspaceEntry,
} from "./selfmod/index.ts";
export {
  runBudgetCheck,
  runReflection,
  runIdleCheck,
  runHeartbeatTick,
  DEFAULT_SCHEDULE,
  type HeartbeatResult,
  type HeartbeatContext,
  type HeartbeatSchedule,
  type HeartbeatTick,
} from "./heartbeat/index.ts";
export {
  parseConstitution,
  defaultConstitution,
  DEFAULT_CONSTITUTION_TEXT,
  evaluateShell,
  evaluatePath,
  evaluateSpawn,
  evaluateRateLimit,
  formatDecision,
  RATE_LIMITS,
  type ConstitutionLaw,
  type ConstitutionRule,
  type ParsedConstitution,
  type Severity,
  type PolicyDecision,
  type ShellPolicyInput,
  type PathPolicyInput,
  type SpawnPolicyInput,
  type RateLimitState,
} from "./policy/index.ts";
export {
  protectAgent,
  unprotectAgent,
  isProtected,
  listProtected,
  scanCullCandidates,
  executeCull,
  checkSelfCull,
  DEFAULT_THRESHOLDS,
  type CullThresholds,
  type CullCandidate,
  type CullScanResult,
  type SelfCullDecision,
} from "./selection/index.ts";
export {
  createRun,
  markRunStarted,
  markRunEnded,
  getRun,
  listRuns,
  appendEvent,
  getEvents,
  countEvents,
  deleteRun,
  resetSeq,
  validateConfig,
  parseConfigYaml,
  PRESETS,
  listPresets,
  getPreset,
  resolveConfig,
  startRun,
  getRunStatus,
  computeMetrics,
  diffRuns,
  formatMetrics,
  exportEventsJsonl,
  getReplayFrames,
  renderFrameSummary,
  computeTimelineSnapshot,
  renderAsciiTreeAtTime,
  type EventKind,
  type ExperimentRun,
  type ExperimentEvent,
  type CreateRunInput,
  type ExperimentConfig,
  type AgentSpec,
  type TaskSpec,
  type Preset,
  type RunOptions,
  type RunResult,
  type RunStatus,
  type RunMetrics,
  type DiffResult,
  type ReplayFrame,
  type TimelineSnapshot,
} from "./experiment/index.ts";
